---
title: "Game"
author: "Leonard-Allen"
date: "2023-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Game
This game generates a random number between 1 and 100 and asks the user to guess the number. The program provides feedback on whether the guess is too high or too low, and keeps track of the number of guesses made. When the user correctly guesses the number, the program displays the number of guesses made and ends the game.


```{r}
# Generate a random number between 1 and 100
random_number <- sample(1:100, 1)

# Start the game
cat("I'm thinking of a number between 1 and 100. Can you guess what it is?\n")

# Set initial guess count to 0
guess_count <- 0

# Start the loop
repeat {
  # Ask for user input
  user_guess <- readline("Enter your guess: ")
  
  # Convert user input to a number
  user_guess <- as.integer(user_guess)
  
  # Check if guess is correct
  if (user_guess == random_number) {
    guess_count <- guess_count + 1
    cat("Congratulations! You guessed the number in", guess_count, "guesses.\n")
    break
  }
  
  # Check if guess is too high
  if (user_guess > random_number) {
    cat("Your guess is too high. Try again.\n")
    guess_count <- guess_count + 1
    next
  }
  
  # Check if guess is too low
  if (user_guess < random_number) {
    cat("Your guess is too low. Try again.\n")
    guess_count <- guess_count + 1
    next
  }
}

# End of game
cat("Thanks for playing! Goodbye.")

```

